import json

from PyQt5 import QtWidgets, QtCore
from PyQt5.QtGui import QImage, QPixmap
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow

from PyQt5 import QtCore, QtGui, QtWidgets

class ControlPanel(QMainWindow):
    def __init__(self, config_file='state.json'):
        super(ControlPanel, self).__init__()
        self.setupUi()

        with open(config_file, 'r') as f:
            self.state = json.load(f)

        # red
        self.mag_r.valueChanged.connect(self.change_state)
        self.upper_r.valueChanged.connect(self.change_state)
        self.lower_r.valueChanged.connect(self.change_state)
        self.binary_r.stateChanged.connect(self.change_state)
        # blue
        self.mag_b.valueChanged.connect(self.change_state)
        self.upper_b.valueChanged.connect(self.change_state)
        self.lower_b.valueChanged.connect(self.change_state)
        self.binary_b.stateChanged.connect(self.change_state)
        # greeen
        self.mag_g.valueChanged.connect(self.change_state)
        self.upper_g.valueChanged.connect(self.change_state)
        self.lower_g.valueChanged.connect(self.change_state)
        self.binary_g.stateChanged.connect(self.change_state)
        # black
        self.mag_k.valueChanged.connect(self.change_state)
        self.upper_k.valueChanged.connect(self.change_state)
        self.lower_k.valueChanged.connect(self.change_state)
        self.binary_k.stateChanged.connect(self.change_state)

    def get_state(self):
        return self.state

    @QtCore.pyqtSlot(int)
    def change_state(self, val):
        uiField = self.sender()
        uiFieldName = str(uiField.objectName())
        uiParentName = str(uiField.parent().objectName())

        self.state["qt_lut"][uiParentName][uiFieldName] = val
        #print(val, uiFieldName, uiParentName)

    def setupUi(self):
        self.setObjectName("ControlPanel")
        self.resize(800, 600)
        self.setStyleSheet("background-color: rgb(118, 118, 118);")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Impact Label")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.red = QtWidgets.QFrame(self.groupBox)
        self.red.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 10px;")
        self.red.setFrameShape(QtWidgets.QFrame.Box)
        self.red.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.red.setLineWidth(2)
        self.red.setObjectName("red")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.red)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mag_r = QtWidgets.QDial(self.red)
        self.mag_r.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.mag_r.setStyleSheet("image: url(:/forground.png);")
        self.mag_r.setWrapping(True)
        self.mag_r.setNotchesVisible(True)
        self.mag_r.setObjectName("mag_r")
        self.gridLayout_5.addWidget(self.mag_r, 0, 0, 1, 1)
        self.upper_r = QtWidgets.QDial(self.red)
        self.upper_r.setStyleSheet("")
        self.upper_r.setWrapping(True)
        self.upper_r.setNotchesVisible(True)
        self.upper_r.setObjectName("upper_r")
        self.gridLayout_5.addWidget(self.upper_r, 1, 0, 1, 1)
        self.lower_r = QtWidgets.QDial(self.red)
        self.lower_r.setStyleSheet("")
        self.lower_r.setWrapping(True)
        self.lower_r.setNotchesVisible(True)
        self.lower_r.setObjectName("lower_r")
        self.gridLayout_5.addWidget(self.lower_r, 2, 0, 1, 1)
        self.binary_r = QtWidgets.QCheckBox(self.red)
        self.binary_r.setText("")
        self.binary_r.setObjectName("binary_r")
        self.gridLayout_5.addWidget(self.binary_r, 3, 0, 1, 1)
        self.binary_r.raise_()
        self.lower_r.raise_()
        self.upper_r.raise_()
        self.mag_r.raise_()
        self.gridLayout.addWidget(self.red, 0, 0, 1, 1)
        self.blue = QtWidgets.QFrame(self.groupBox)
        self.blue.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.blue.setFrameShape(QtWidgets.QFrame.Box)
        self.blue.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.blue.setLineWidth(2)
        self.blue.setObjectName("blue")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.blue)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.mag_b = QtWidgets.QDial(self.blue)
        self.mag_b.setStyleSheet("")
        self.mag_b.setWrapping(True)
        self.mag_b.setNotchesVisible(True)
        self.mag_b.setObjectName("mag_b")
        self.gridLayout_3.addWidget(self.mag_b, 0, 0, 1, 1)
        self.upper_b = QtWidgets.QDial(self.blue)
        self.upper_b.setStyleSheet("")
        self.upper_b.setWrapping(True)
        self.upper_b.setNotchesVisible(True)
        self.upper_b.setObjectName("upper_b")
        self.gridLayout_3.addWidget(self.upper_b, 1, 0, 1, 1)
        self.lower_b = QtWidgets.QDial(self.blue)
        self.lower_b.setStyleSheet("")
        self.lower_b.setWrapping(True)
        self.lower_b.setNotchesVisible(True)
        self.lower_b.setObjectName("lower_b")
        self.gridLayout_3.addWidget(self.lower_b, 2, 0, 1, 1)
        self.binary_b = QtWidgets.QCheckBox(self.blue)
        self.binary_b.setText("")
        self.binary_b.setObjectName("binary_b")
        self.gridLayout_3.addWidget(self.binary_b, 3, 0, 1, 1)
        self.binary_b.raise_()
        self.lower_b.raise_()
        self.mag_b.raise_()
        self.upper_b.raise_()
        self.gridLayout.addWidget(self.blue, 0, 1, 1, 1)
        self.green = QtWidgets.QFrame(self.groupBox)
        self.green.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.green.setFrameShape(QtWidgets.QFrame.Box)
        self.green.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.green.setLineWidth(2)
        self.green.setObjectName("green")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.green)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.mag_g = QtWidgets.QDial(self.green)
        self.mag_g.setStyleSheet("")
        self.mag_g.setWrapping(True)
        self.mag_g.setNotchesVisible(True)
        self.mag_g.setObjectName("mag_g")
        self.gridLayout_4.addWidget(self.mag_g, 0, 0, 1, 1)
        self.upper_g = QtWidgets.QDial(self.green)
        self.upper_g.setStyleSheet("")
        self.upper_g.setWrapping(True)
        self.upper_g.setNotchesVisible(True)
        self.upper_g.setObjectName("upper_g")
        self.gridLayout_4.addWidget(self.upper_g, 1, 0, 1, 1)
        self.lower_g = QtWidgets.QDial(self.green)
        self.lower_g.setStyleSheet("")
        self.lower_g.setWrapping(True)
        self.lower_g.setNotchesVisible(True)
        self.lower_g.setObjectName("lower_g")
        self.gridLayout_4.addWidget(self.lower_g, 2, 0, 1, 1)
        self.binary_g = QtWidgets.QCheckBox(self.green)
        self.binary_g.setText("")
        self.binary_g.setObjectName("binary_g")
        self.gridLayout_4.addWidget(self.binary_g, 3, 0, 1, 1)
        self.binary_g.raise_()
        self.lower_g.raise_()
        self.upper_g.raise_()
        self.mag_g.raise_()
        self.gridLayout.addWidget(self.green, 0, 2, 1, 1)
        self.black = QtWidgets.QFrame(self.groupBox)
        self.black.setStyleSheet("background-color: rgb(10,10,10);")
        self.black.setFrameShape(QtWidgets.QFrame.Box)
        self.black.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.black.setLineWidth(2)
        self.black.setObjectName("black")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.black)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mag_k = QtWidgets.QDial(self.black)
        self.mag_k.setStyleSheet("")
        self.mag_k.setWrapping(True)
        self.mag_k.setNotchesVisible(True)
        self.mag_k.setObjectName("mag_k")
        self.gridLayout_2.addWidget(self.mag_k, 0, 0, 1, 1)
        self.upper_k = QtWidgets.QDial(self.black)
        self.upper_k.setStyleSheet("")
        self.upper_k.setWrapping(True)
        self.upper_k.setNotchesVisible(True)
        self.upper_k.setObjectName("upper_k")
        self.gridLayout_2.addWidget(self.upper_k, 1, 0, 1, 1)
        self.lower_k = QtWidgets.QDial(self.black)
        self.lower_k.setStyleSheet("")
        self.lower_k.setWrapping(True)
        self.lower_k.setNotchesVisible(True)
        self.lower_k.setObjectName("lower_k")
        self.gridLayout_2.addWidget(self.lower_k, 2, 0, 1, 1)
        self.binary_k = QtWidgets.QCheckBox(self.black)
        self.binary_k.setText("")
        self.binary_k.setObjectName("binary_k")
        self.gridLayout_2.addWidget(self.binary_k, 3, 0, 1, 1)
        self.upper_k.raise_()
        self.mag_k.raise_()
        self.binary_k.raise_()
        self.lower_k.raise_()
        self.gridLayout.addWidget(self.black, 0, 3, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("ControlPanel", "MainWindow"))
        self.groupBox.setTitle(_translate("ControlPanel", "COLORS"))


